version: '3'
services:
  mlflow:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./mlflow:/app/mlflow
    environment:
      MLFLOW_S3_ENDPOINT_URL: https://s3.amazonaws.com
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
